### ISSUE TITLE
Enhance Test System

### ISSUE THREAD

**Issue by lazaridiscom** [GridPlus/cryptobridge-contracts#16]
### Tasks 

(draft)

- [ ] Split down larger test files into separate files
- [ ] Separate unit and integration tests
- [ ] Provide Mock and Real Integration test

### Requirements

* Ensure that existent test-mechanisms are reused
* Ensure that test-system can be reused

(affects #11, but is out of its scope. Should be provided in future)

**Comment by lazaridiscom** [comment]
moved to #20
